=== Endless-Fighting/DailyLearning/XML/homework2/SpyBase2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 被2013 sp1 () 使用XMLSpy v编辑的 (http://www.altova.com) by -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="info">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="spy" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="alias" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="aID">
												<xs:simpleType>
													<xs:restriction base="xs:integer">
														<xs:minInclusive value="1"/>
														<xs:maxInclusive value="7"/>
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="mission" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="date">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:pattern value="\d{4}/\d{1,2}/\d{1,2}"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="description" type="xs:string"/>
										<xs:element name="status">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="Mission Accomplished"/>
													<xs:enumeration value="In Progress"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="mID" type="xs:string"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="spyID" type="xs:string"/>
						<xs:attribute name="firstName"/>
						<xs:attribute name="lastName"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Endless-Fighting/DailyLearning/XML/homework2/SpyBase2.xml
<?xml version="1.0"?>
<!-- 被2013 sp1 () 使用XMLSpy v编辑的 (http://www.altova.com) by -->
<info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SpyBase2.xsd">
	<spy spyID="A001" firstName="Nikki" lastName="Devgood">
		<alias aID="1">Spy Grrrl</alias>
		<alias aID="2">LaFemme Nikki</alias>
		<mission mID="M101">
			<date>2005/4/15</date>
			<description>Crack the code</description>
			<status>Mission Accomplished</status>
		</mission>
		<mission mID="M102">
			<date>2006/2/15</date>
			<description>Get the source</description>
			<status>Mission Accomplished</status>
		</mission>
		<mission mID="M103">
			<date>2006/5/4</date>
			<description>Hit the target</description>
			<status>In Progress</status>
		</mission>
	</spy>
	<spy spyID="A006" firstName="Link" lastName="Lister">
		<alias aID="3">LL</alias>
		<alias aID="4">Fred</alias>
		<mission mID="M104">
			<date>2006/6/15</date>
			<description>Shoot the rapid</description>
			<status>In Progress</status>
		</mission>
	</spy>
	<spy spyID="A003" firstName="Danger" lastName="Mause">
		<alias aID="5">Big Ears</alias>
		<mission mID="M105">
			<date>2005/11/4</date>
			<description>Get the &lt;big cheese&gt;</description>
			<status>In Progress</status>
		</mission>
		<mission mID="M106">
			<date>2006/4/4</date>
			<description>Map the area</description>
			<status>In Progress</status>
		</mission>
	</spy>
	<spy spyID="A099" firstName="Barbara" lastName="Feldon">
		<mission mID="M107">
			<date>2006/5/2</date>
			<description>Get Smart</description>
			<status>In Progress</status>
		</mission>
	</spy>
	<spy spyID="A004" firstName="Maxwell" lastName="Smart">
		<alias aID="6">Inspector Gadget</alias>
		<alias aID="7">Don Adams</alias>
		<mission mID="M108">
			<date>1967/2/15</date>
			<description>Protect Chief</description>
			<status>In Progress</status>
		</mission>
		<mission mID="M109">
			<date>2006/6/15</date>
			<description>Get some style</description>
			<status>Mission Accomplished</status>
		</mission>
	</spy>
</info>
